### ISSUE TITLE
/getSingleImage query returning {"errorMessage":"java.lang.IndexOutOfBoundsException: Index: 0, Size: 0"}

### ISSUE THREAD

**Issue by liam-ot** [TCIA-Community/TCIA-API-SDK#6]
Using Python3 on a jupyter notebook, I am building an application which gets images from TCIA.

The query being sent is:
`https://services.cancerimagingarchive.net/services/v4/TCIA/query/getSingleImage?SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.5168.1900.104193299251798317056218297018&SOPInstanceUID=1.3.6.1.4.1.14519.5.2.1.5168.1900.313476290902233915328110338498]&format=lxml`

the error code returned is:
`{"errorMessage":"java.lang.IndexOutOfBoundsException: Index: 0, Size: 0"}`

the query is built by this function, which takes the params `series` and `sop`, both of which are lists of tuples, containing SeriesInstanceUID's and SOPInstanceUID's respectively:
```
def get_single_image(self, series, sop):

        # format SeriesInstanceUID parameter
        series_param='SeriesInstanceUID='+series[0][1]

        # format SOPInstanceUID parameter
        sop_param='SOPInstanceUID='+sop[0][1]

        image=requests.get(self.base + 
                           self.resource +
                           self.get_single_img_qry + '?' +
                           series_param + '&' +
                           sop_param + '&' +
                           self.lxml_format).text
        return image

```
I checked and the lists passed to `get_single_image` which return the error message are not empty and are properly formatted

**Comment by liam-ot** [comment]
Also thank you to the dev team for creating this API you are all doing amazing, meaningful work

**Comment by pradeeban** [comment]
You have some typos in your query.

https://services.cancerimagingarchive.net/services/v4/TCIA/query/getSingleImage?SeriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.5168.1900.104193299251798317056218297018&SOPInstanceUID=1.3.6.1.4.1.14519.5.2.1.5168.1900.313476290902233915328110338498&format=xml


And thanks for your appreciation. :)

**Comment by liam-ot** [comment]
thanks man sorry for the silly mistake
